### ISSUE TITLE
全角文字が極端に少ないshift-jisの文章を開けないことがある

### ISSUE THREAD

**Issue by kurehajime** [Hiromi-Ayase/brackets-shizimily-multiencoding#1]
#### 現象① エラーが発生し開くことが出来ないパターン

テキストエディタで「初音ミク」とだけ書き込みshift-jisで保存し、Bracketsで開く。
このファイルは正常に開くことができる。

次にテキストエディタで「初音」とだけ書き込みshift-jisで保存し、Bracketsで開く。
「ファイルを開く際にエラーが発生しました。」というエラーメッセージが表示される。
#### 現象② 文字化けが発生するパターン

テキストエディタで「すもももももももものうち」とだけ書き込みshift-jisで保存し、Bracketsで開く。
このファイルは正常に開くことができる。

次にテキストエディタで「すもも」とだけ書き込みshift-jisで保存し、Bracketsで開く。
文字化けが発生する。(エンコードがwindows-1252として判定される)
#### 補足

「初音初音初音初音初音初音」とエラーパターンを繰り返してもエラーは解消されない。
「初音Hello WorldHello WorldHello World」と半角文字を付け足してもエラーは解消されない。
「初音Hello WorldHello WorldHello Worldミク」と有効な全角文字を付け足すと正常に開くことができる。

条件は不明だが、わりと大きめ(500行over)のファイルでも全角文字の割合が少ないと
有効な全角文字(例：ミク)を付け足してもエラーが発生することがある。
その場合でも有効な文字列を大量(例：ミク×10回)に付加すると正常に開くことができる。
付け足さなければならない有効な文字の量は全体の文字数に比例する(?)。
#### 暫定的な回避策

現象②に関しては、文字コードをShift-jisに変更すると正常に開くことができ、同名のファイルなら次開いた時も文字コードが記憶される。
現象①に関しては上記の対応策は効かず。(開けないので)
### 現象が発生した環境

Windows 7 
Brackets 1.2.0-15697
Shizimily Multiencoding for Brackets 0.0.7

**Comment by kurehajime** [comment]
現象①の方はshizimilyDomain.jsの21行目で
`Error while detecting encoding : Confidence = 0`
と例外を吐いてるようなので、このパターンの時にユーザーが指定した
エンコードで強制的に開くオプションがあれば良いなぁ。

**Comment by Hiromi-Ayase** [comment]
報告ありがとうございます。強制的にファイルを開くForceオプションを付けました。

**Comment by kurehajime** [comment]
対応ありがとうございます。
お陰でBracketsの利用がとても捗るようになりました。
