### ISSUE TITLE
拡張機能をインストールするとBracketsがフリーズします。

### ISSUE THREAD

**Issue by umyuu** [Hiromi-Ayase/brackets-shizimily-multiencoding#8]
ファイルメニュー→拡張機能マネージャーも開くことができなくなります。

以下のような質問が乱立しているので、拡張機能のストアから削除して頂くことは可能でしょうか？
[Brackets 動かない…！](https://teratail.com/questions/130645)
[brackets 保存する際にエラーが出ます。](https://teratail.com/questions/105702)
[Bracketsで保存ができなくて困っています](https://teratail.com/questions/91420)

[The program window starts and hangs, it is impossible to close the program (windows 10)](https://github.com/adobe/brackets/issues/13537) by adobe/bracketsのGitHub

**Comment by Hiromi-Ayase** [comment]
削除しました。

**Comment by umyuu** [comment]
対応ありがとうございました。
